### ISSUE TITLE
Magic number 0.078

### ISSUE THREAD

**Issue by rwestlund** [vanallen/writeup#26]
You use 0.078 as a magic probability of a wrong answer in chapter 4. You should explain where this number comes from.

https://github.com/vanallen/writeup/blob/a2c3c8fe0b8d8ae5e24df0fea72764c5563c5971/chap4.tex#L175

**Comment by vanallen** [comment]
Should I add that to appendix or should I explain it in the paper?

**Comment by rwestlund** [comment]
I'd explain it in the paper, the first time you use it.
