### ISSUE TITLE
Paragraph ordering in Intro

### ISSUE THREAD

**Issue by rwestlund** [vanallen/writeup#41]
This paragraph is explaining the first improvement being made to Sloop.  As it is, the reader doesn't understand the purpose of the paragraph until reaching the end.  It should start with something like, "The first improvement made ..." Then finish the sentence with the content of the current last sentence.

https://github.com/vanallen/writeup/blob/8638f01c26a32d0976c027c7016a662394cbdfb8/chap1.tex#L47-L55

This paragraph has the same problem:
https://github.com/vanallen/writeup/blob/8638f01c26a32d0976c027c7016a662394cbdfb8/chap1.tex#L57-L67

**Comment by vanallen** [comment]
Fixed this. Please take a look at the most recent change.

**Comment by rwestlund** [comment]
Looks good to me :)
