### ISSUE TITLE
Group similar information in chapter 1

### ISSUE THREAD

**Issue by rwestlund** [vanallen/writeup#43]
There no need to discuss the same thing twice.  Merge this:
https://github.com/vanallen/writeup/blob/8638f01c26a32d0976c027c7016a662394cbdfb8/chap1.tex#L75-L80
into the paragraph about relevance feedback in the introduction:
https://github.com/vanallen/writeup/blob/8638f01c26a32d0976c027c7016a662394cbdfb8/chap1.tex#L57-L67

Similarly, merge
https://github.com/vanallen/writeup/blob/8638f01c26a32d0976c027c7016a662394cbdfb8/chap1.tex#L82-L95
into
https://github.com/vanallen/writeup/blob/8638f01c26a32d0976c027c7016a662394cbdfb8/chap1.tex#L35-L45

**Comment by vanallen** [comment]
I feel that some readers usually skip the introduction since most of them are not succinct. I would like to summarize my goals in problem statements so that such group of readers can just jump right to this section instead of having to go through the whole introduction.

**Comment by vanallen** [comment]
For relevance feedback section:
The intro lists the benefits of relevance feedback incorporation, but it does not say anything about our goal.
Same for CNN. Intro suggests that CNN is good, but problem statement explains how it is going to be integrated.

**Comment by rwestlund** [comment]
Don't plan on people skipping parts of your paper; that makes it poorly-written for people who actually read it.  Make it a coherent story.  Think of it as a narrative; you're telling the story of what the problem is and how you solved it.

You can call it Problem Statements or Introduction or whatever you like, but everything about relevance feedback should be together, and everything CNN-related should be together.  Then you get the story of what there is, and why you're using it, and what you're doing with it.

**Comment by vanallen** [comment]
Randy, I have restructured the introduction and grouped similar information together. Please let me know if it looks okay to you.

**Comment by rwestlund** [comment]
This looks a lot better now :)
