### ISSUE TITLE
Trim information retrieval in chapter 2

### ISSUE THREAD

**Issue by rwestlund** [vanallen/writeup#46]
The information retrieval section in chapter 2 is full of a lot of fluff that you obviously just rephrased from wikipedia.  Remove most of it; it isn't relevant to what you're trying to say.  In particular, this section should:
- Define 'information retrieval' in one sentence.
- Don't talk about databases or query structure.
- Answer the question, "how does information retrieval benefit us here?" hint: It's about providing pairs to examine.
- Be only one short paragraph at the most.

https://github.com/vanallen/writeup/blob/c3074ca666065650a0c5367fe9f8670e6f15e931/chap2.tex#L15-L30

**Comment by vanallen** [comment]
Randy, I have removed the section and rewrite chapter 2 to capture more information on related researches. Please let me know how you think.

**Comment by rwestlund** [comment]
Sorry for the delay.  This looks much better now :)
