### ISSUE TITLE
Plagiarizing Wikipedia

### ISSUE THREAD

**Issue by rwestlund** [vanallen/writeup#7]
You copied this paragraph almost verbatim from Wikipedia:
https://github.com/vanallen/writeup/blob/c8eada7410066587a0a4e8ee66817dea593d5d85/chap5.tex#L111-L114

Original:
https://en.wikipedia.org/wiki/Amazon_Mechanical_Turk

You can't do this, Navi.  It's plagiarism.  They could fail you for this, or worse.  Either cite Wikipedia properly or explain it in your own words.  You'd better make sure you didn't do this anywhere else in your paper.

If you're not clear on this, read MIT's guidelines. They have several articles (see the left sidebar) that explain it.
https://integrity.mit.edu/handbook/what-plagiarism

**Comment by vanallen** [comment]
Thank you Randy for pointing this out. I must have place the paragraph so that I can paraphrase without having to look it up again, but eventually, I forgot and left it there.
